### ISSUE TITLE
can't compile on windows

### ISSUE THREAD

**Issue by vcvrackideas** [aaronstatic/AaronStatic_modules#1]
Hi and thanks! but I can't compile on windows - Makefile:23: /e/Projects/vcv-rack/Rack-SDK/plugin.mk: No such file or directory

**Comment by aaronstatic** [comment]
Hi vcvrackideas!, youll need to set an environment variable "RACK_DIR" with the location of your VCV Rack SDK. Or you can edit the Makefile and replace it at the top. See https://vcvrack.com/manual/Building#building-rack-plugins

**Comment by aaronstatic** [comment]
Or here is a windows build for you, just drop it in your My Documents/Rack/plugins-v1 folder

[AaronStatic-1.0.0-win.zip](https://github.com/aaronstatic/AaronStatic_modules/files/4123804/AaronStatic-1.0.0-win.zip)
