### ISSUE TITLE
Chord CV second inversion - unexpected chord shape

### ISSUE THREAD

**Issue by lynxnot** [aaronstatic/AaronStatic_modules#14]
Hello, 
I was using the Chord CV module to reproduce a song and noticed that the third note of the second inversion is actually not what one would expect. For instance:

**C/G**
```
Expected: G4 - C5 - E5
Chord CV: G4 - C5 - G4
```
The third note is a repetition of the first G4. The same happens with other chords types:

**Dm/A** 

```
Expected: A3 - D4 - F4
Chord CV: A3 - D4 - A3
```
Again a repetition of the first note. 

Seems systematic on the second inversion, but I have only tested the two here that I needed.

**Comment by aaronstatic** [comment]
Will be fixed in v2.0.1 when pushed to VCV library
