### ISSUE TITLE
With MIDI CV -> Chord its impossible to control chord (DiatonicCV) from midi kbd

### ISSUE THREAD

**Issue by sergeyg-foxway** [aaronstatic/AaronStatic_modules#16]
Hey guys! Thank you for your totally great modules but I have a problem. A bit unusable situation, cause 100% modules minus DiatonicCV are fully and correctly controllable without any issue with midi v/oct output. Tried some multipliers (another story like 1 * 1 + 0 = 2 but its not about AaronStatic). Without multipliers it moves from C to Em (DiatonicCV module) while Im using 2 octaves on kbd from C to C.

mb I dont understand smth (like CV from midi kbd raises with any new octave), but at least it has to work at least for 1 octave.

PS: Im trying to control chord with pressing 1 key on midi kbd.

**Comment by aaronstatic** [comment]
The input is not 1v/oct, it is selecting the chord within the scale (1-7) and doesnt make sense to be 1v/oct
