### ISSUE TITLE
Poly out bug

### ISSUE THREAD

**Issue by vcvrackideas** [aaronstatic/AaronStatic_modules#2]
Hi! Just found that poly output sends only 3 channels instead of expected 4.
![2020-01-29_21-03-18](https://user-images.githubusercontent.com/42435368/73383724-ef1a3f80-42da-11ea-98a4-f7cd84b169b7.png)

**Comment by aaronstatic** [comment]
It sends 3 channels if the chord is a triad. It sends 4 channels only for seventh chords. This is by design
